[project]
name = "clase-python"
version = "0.1.0"
description = "Entorno para alumnos"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "matplotlib",
    "requests",
    "numpy",
    "matplotlib",
    "scikit-learn",
    "ipykernel",
    "shap>=0.51.0",
    "seaborn>=0.13.2",
]
